version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:15
    steps:
      - run: echo "hello world" > ~/output.txt
      - run: return 1
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
      - run:
          name: on error
          command: echo "Hello Error!"
          when: on_fail

  print_output_file:
    docker:
      - image: circleci/node:15
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
      - print_pipeline_id

workflows:
  my_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output